# Generated by Django 3.2.9 on 2021-11-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=16, unique=True, verbose_name='user_id')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('user_name', models.CharField(max_length=10, verbose_name='user_name')),
                ('department', models.CharField(max_length=30, verbose_name='Department')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
