# Generated by Django 3.2.9 on 2021-11-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.IntegerField(unique=True)),
                ('start_date', models.CharField(max_length=15, verbose_name='start_date')),
                ('end_date', models.CharField(max_length=15, verbose_name='end_date')),
                ('booth_host', models.CharField(max_length=10, verbose_name='booth_host')),
                ('booth_name', models.CharField(max_length=30, verbose_name='booth_name')),
                ('booth_explain', models.TextField(max_length=150, verbose_name='booth_explain')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=30, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=30, verbose_name='longitude')),
                ('building_name', models.CharField(max_length=30, verbose_name='building_name')),
                ('is_building', models.BooleanField(default=True, verbose_name='is_building')),
            ],
        ),
    ]
