# Generated by Django 3.2.9 on 2021-11-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_map_building_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='building_info',
            field=models.CharField(max_length=500, null=True, verbose_name='building_info'),
        ),
    ]
