# Generated by Django 3.2.9 on 2021-12-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_buildinginfo_info_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('user_latitude', models.DecimalField(decimal_places=6, max_digits=30, verbose_name='latitude')),
                ('user_longitude', models.DecimalField(decimal_places=6, max_digits=30, verbose_name='longitude')),
            ],
        ),
    ]
