# Generated by Django 3.2.9 on 2021-12-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_userlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='map',
            name='is_building',
            field=models.IntegerField(default=0, verbose_name='is_building'),
        ),
    ]
