# Generated by Django 3.2.9 on 2021-11-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(verbose_name='bus_schedule_index')),
                ('schedule_school', models.CharField(max_length=8, null=True, verbose_name='bus_schedule_school')),
                ('schedule_station', models.CharField(max_length=8, null=True, verbose_name='bus_schedule_station')),
                ('is_holiday', models.IntegerField(verbose_name='is_holiday')),
            ],
        ),
    ]
